version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'ci:'
    labels:
      - "ci"
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'build:'
    labels:
      - 'dependencies'
